server:
  port: 8080
spring:
  jpa:
    open-in-view: false
  datasource:
    url: jdbc:mysql://localhost:3306/mochen_wu?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: minchenww7
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 50MB

logging:
  level:
    org:
      springframework:
        jdbc: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  reasonable: false
  defaultCount: true

